from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    DateTime,
    Float,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
    UniqueConstraint,
)
from sqlalchemy.sql import func


metadata = MetaData()

klines = Table(
    "klines",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("exchange", String(32), nullable=False),
    Column("symbol", String(64), nullable=False),
    Column("interval", String(16), nullable=False),
    Column("open_time", DateTime, nullable=False),
    Column("close_time", DateTime, nullable=False),
    Column("open", Numeric, nullable=False),
    Column("high", Numeric, nullable=False),
    Column("low", Numeric, nullable=False),
    Column("close", Numeric, nullable=False),
    Column("volume", Numeric, nullable=False),
    Column("quote_volume", Numeric),
    Column("is_closed", Boolean, default=True),
    Column("created_at", DateTime, server_default=func.now()),
    UniqueConstraint("exchange", "symbol", "interval", "open_time"),
)

indicators = Table(
    "indicators",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("exchange", String(32), nullable=False),
    Column("symbol", String(64), nullable=False),
    Column("interval", String(16), nullable=False),
    Column("ts", DateTime, nullable=False),
    Column("atr", Float),
    Column("macd", Float),
    Column("macd_signal", Float),
    Column("macd_hist", Float),
    Column("vwap", Float),
    Column("cvd", Float),
    Column("delta", Float),
    Column("structure_state", JSON),
    Column("created_at", DateTime, server_default=func.now()),
    UniqueConstraint("exchange", "symbol", "interval", "ts"),
)

strategy_states = Table(
    "strategy_states",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("strategy_id", String(128), nullable=False),
    Column("exchange", String(32), nullable=False),
    Column("symbol", String(64), nullable=False),
    Column("book", String(16), nullable=False),
    Column("strategy_name", String(128), nullable=False),
    Column("state", String(32), nullable=False),
    Column("direction", String(16)),
    Column("context", JSON),
    Column("last_signal_id", String(128)),
    Column("entered_state_at", DateTime),
    Column("updated_at", DateTime, server_default=func.now(), onupdate=func.now()),
    UniqueConstraint("strategy_id", "exchange", "symbol"),
)

signals = Table(
    "signals",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("signal_id", String(128), unique=True, nullable=False),
    Column("exchange", String(32), nullable=False),
    Column("symbol", String(64), nullable=False),
    Column("book", String(16), nullable=False),
    Column("strategy_name", String(128), nullable=False),
    Column("level", String(8), nullable=False),
    Column("direction", String(16)),
    Column("status", String(32)),
    Column("trigger_price", Numeric),
    Column("entry", Numeric),
    Column("sl", Numeric),
    Column("tp1", Numeric),
    Column("tp2", Numeric),
    Column("tp3", Numeric),
    Column("rr_to_tp1", Float),
    Column("position_r", Float),
    Column("trigger_reason", Text),
    Column("invalid_condition", Text),
    Column("risk_flags", JSON),
    Column("btc_filter", JSON),
    Column("flow_state", JSON),
    Column("raw_snapshot", JSON),
    Column("created_at", DateTime, server_default=func.now()),
    Column("expired_at", DateTime),
    Column("resolved_at", DateTime),
    Column("result", String(32)),
    Column("tp1_reached", Boolean, default=False),
    Column("sl_reached", Boolean, default=False),
)

notifications = Table(
    "notifications",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("signal_id", String(128)),
    Column("channel", String(32)),
    Column("target", String(128)),
    Column("title", Text),
    Column("body", Text),
    Column("status", String(32)),
    Column("retry_count", Integer, default=0),
    Column("error_message", Text),
    Column("sent_at", DateTime),
    Column("created_at", DateTime, server_default=func.now()),
)

indicator_archives = Table(
    "indicator_archives",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("run_id", String(64), unique=True, nullable=False),
    Column("generated_at", DateTime, nullable=False),
    Column("payload", JSON, nullable=False),
    Column("created_at", DateTime, server_default=func.now()),
)
