symbols:
  - exchange: BINANCE
    symbol: ETHUSDT
    enabled: true
    type: PERPETUAL
    intervals: ["5m", "15m", "1h", "4h", "1d"]

  - exchange: BINANCE
    symbol: BTCUSDT
    enabled: true
    type: PERPETUAL
    intervals: ["15m", "1h", "4h", "1d"]
